name: Deploy to Local Ubuntu Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Pull latest code
        run: |
          cd /home/hoang-an/web-chat
          git pull origin main

      - name: Restart Web Server
        run: |
          sudo systemctl restart webchat.service